export const ADD_NEW_CITY = 'ADD_NEW_CITY';
export const REMOVE_CITY = 'REMOVE_CITY';

export const ADD_CITY_DETAILS_START = 'ADD_CITY_DETAILS_START';
export const ADD_CITY_DETAILS_SUCCESS = 'ADD_CITY_DETAILS_SUCCESS';
export const ADD_CITY_DETAILS_ERROR = 'ADD_CITY_DETAILS_ERROR';
